[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "aarch64-linux-musl-ld"

[target.riscv64gc-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "riscv64-linux-musl-ld"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=-crt-static"]
linker = "x86_64-linux-musl-ld"
